import { useEffect, useState } from "react"
import { Link, useNavigate } from "react-router-dom"

import { Button } from "@/components/ui/button"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldSeparator,
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { useAuth } from "@/context/AuthContext"
import { adminRegister } from "@/services/auth"

export function AdminSignupPage() {
  const navigate = useNavigate()
  const { isAuthenticated, setSession } = useAuth()

  const [fullName, setFullName] = useState("")
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")
  const [adminSignupKey, setAdminSignupKey] = useState("")
  const [loading, setLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/", { replace: true })
    }
  }, [isAuthenticated, navigate])

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setLoading(true)
    setErrorMessage(null)

    try {
      const response = await adminRegister({
        fullName: fullName.trim(),
        email: email.trim(),
        password,
        confirmPassword,
        adminSignupKey: adminSignupKey.trim(),
      })

      if (!response.token) {
        throw new Error("No token received from server")
      }

      setSession(response.token.replace(/^Bearer\s+/i, ""), response.user)
      navigate("/", { replace: true })
    } catch (error) {
      const message = error instanceof Error ? error.message : "Admin registration failed"
      setErrorMessage(message)
      setLoading(false)
    }
  }

  return (
    <main className="relative min-h-svh overflow-hidden bg-[#f7f8f8] text-[#191a1b]">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_18%_18%,rgba(113,112,255,0.18),transparent_42%),radial-gradient(circle_at_80%_80%,rgba(94,106,210,0.14),transparent_44%)]" />

      <div className="relative mx-auto grid min-h-svh w-full max-w-5xl place-items-center px-4 py-12 sm:px-6">
        <form
          onSubmit={handleSubmit}
          className="w-full max-w-xl rounded-2xl border border-[#d0d6e0] bg-[#ffffff] p-6 text-[#191a1b] md:p-8"
        >
          <FieldGroup>
            <div className="text-center">
              <p className="text-xs font-[510] uppercase tracking-[0.2em] text-[#7170ff]">Admin Access</p>
              <h1 className="mt-2 text-2xl font-[590] tracking-[-0.028em]">Admin Registration</h1>
              <p className="mt-2 text-sm text-[#62666d]">
                Use your invite key generated by a SUPER_ADMIN to create an ADMIN account.
              </p>
            </div>

            {errorMessage ? <FieldError>{errorMessage}</FieldError> : null}

            <Field>
              <FieldLabel htmlFor="admin-signup-key">Admin Signup Key</FieldLabel>
              <Input
                id="admin-signup-key"
                value={adminSignupKey}
                onChange={(event) => setAdminSignupKey(event.target.value)}
                placeholder="ADM-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX"
                required
                className="border-[#d0d6e0] bg-[#f5f6f7] text-[#191a1b]"
              />
              <FieldDescription>
                This key is single-use and expires automatically.
              </FieldDescription>
            </Field>

            <Field>
              <FieldLabel htmlFor="admin-name">Full Name</FieldLabel>
              <Input
                id="admin-name"
                value={fullName}
                onChange={(event) => setFullName(event.target.value)}
                placeholder="Admin Name"
                required
                className="border-[#d0d6e0] bg-[#f5f6f7] text-[#191a1b]"
              />
            </Field>

            <Field>
              <FieldLabel htmlFor="admin-email">Email</FieldLabel>
              <Input
                id="admin-email"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                placeholder="admin@campus.edu"
                required
                className="border-[#d0d6e0] bg-[#f5f6f7] text-[#191a1b]"
              />
            </Field>

            <Field>
              <FieldLabel htmlFor="admin-password">Password</FieldLabel>
              <Input
                id="admin-password"
                type="password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                required
                className="border-[#d0d6e0] bg-[#f5f6f7] text-[#191a1b]"
              />
            </Field>

            <Field>
              <FieldLabel htmlFor="admin-confirm-password">Confirm Password</FieldLabel>
              <Input
                id="admin-confirm-password"
                type="password"
                value={confirmPassword}
                onChange={(event) => setConfirmPassword(event.target.value)}
                required
                className="border-[#d0d6e0] bg-[#f5f6f7] text-[#191a1b]"
              />
            </Field>

            <Field>
              <Button
                type="submit"
                disabled={loading}
                className="border border-[#5e6ad2] bg-[#5e6ad2] text-white hover:bg-[#7170ff]"
              >
                {loading ? "Creating admin account..." : "Create admin account"}
              </Button>
            </Field>

            <FieldSeparator className="*:data-[slot=field-separator-content]:bg-[#ffffff]">
              Account Access
            </FieldSeparator>

            <FieldDescription className="text-center">
              Already have an account?{" "}
              <Link to="/login" className="text-[#43464b] underline underline-offset-4 hover:text-[#191a1b]">
                Sign in
              </Link>
            </FieldDescription>
            <FieldDescription className="text-center">
              Need a regular user account?{" "}
              <Link to="/signup" className="text-[#43464b] underline underline-offset-4 hover:text-[#191a1b]">
                User sign up
              </Link>
            </FieldDescription>
          </FieldGroup>
        </form>
      </div>
    </main>
  )
}
