spring:
  application:
    name: smart-campus-api


  datasource:
    url: jdbc:postgresql://localhost:5432/SMCSDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false


server:
    port: 8080
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:your_cloud_name}
  api-key: ${CLOUDINARY_API_KEY:your_api_key}
  api-secret: ${CLOUDINARY_API_SECRET:your_api_secret}
  folder: smart-campus-tickets


logging:
  level:
    org.springframework.security: DEBUG