spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:smart-campus-api/.env[.properties]
  application:
    name: smart-campus-api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SMCSDB}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dbda5xjhk}
  api-key: ${CLOUDINARY_API_KEY:658366674114443}
  api-secret: ${CLOUDINARY_API_SECRET:gKtk-zEt_-EFN3u-DtOOElDUkDY}
  folder: smart-campus-tickets

app:
  jwt-secret: ${APP_JWT_SECRET:replace_with_strong_base64_secret}
  jwt-expiration-milliseconds: ${APP_JWT_EXPIRATION_MILLISECONDS:86400000}
  oauth2:
    authorized-redirect-uri: ${APP_OAUTH2_AUTHORIZED_REDIRECT_URI:http://localhost:5173/auth/callback}
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:5173}
  auth:
    allow-dummy-login: ${APP_AUTH_ALLOW_DUMMY_LOGIN:false}
    admin-signup-key-valid-hours: ${APP_AUTH_ADMIN_SIGNUP_KEY_VALID_HOURS:24}

  super-admin:
    email: ${APP_SUPER_ADMIN_EMAIL:}
    password: ${APP_SUPER_ADMIN_PASSWORD:}
    full-name: ${APP_SUPER_ADMIN_FULL_NAME:Super Admin}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

resend:
  api-key: ${RESEND_API_KEY:}
  from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}
